# Site settings
title: Практикум на ЭВМ, семестр 5
email: maxim.zanchurin@gmail.com
description: "

"
baseurl: "/programming-semestr-5/" # the subpath of your site, e.g. /blog/
url: "https://mzanchurin.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  mzanchurin

# Build settings
markdown: kramdown
